<a href="https://colab.research.google.com/github/villaalessandra03-svg/Project_NLP_villa/blob/main/sentence_embeddings_prova1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import files
import pandas as pd

uploaded = files.upload()

df = pd.read_csv("jo_sentences_clustering.csv")

print("Numero di frasi:", len(df))
display(df.head())

Saving jo_sentences_clustering.csv to jo_sentences_clustering (1).csv
Numero di frasi: 1959

,novel,sentence_id,sentence,start_offset,end_offset
0,littlewomen,littlewomen_00001,“Christmas won’t be Christmas without any pres...,74,157
1,littlewomen,littlewomen_00002,The four young faces on which the firelight sh...,469,654
2,littlewomen,littlewomen_00003,"I’ve wanted it so long,” said Jo, who was a bo...",1515,1568
3,littlewomen,littlewomen_00004,"Let’s each buy what we want, and have a little...",1885,2046
4,littlewomen,littlewomen_00005,"“You don’t have half such a hard time as I do,...",2196,2252

In [3]:
%pip install -q sentence-transformers

In [4]:
import torch
from sentence_transformers import SentenceTransformer

# Verifica della GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

print("Dispositivo utilizzato:", device)

if device == "cuda":
    print("GPU:", torch.cuda.get_device_name(0))

# Caricamento del modello
model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2",
    device=device
)

print("Modello caricato correttamente!")
print("Dimensioni degli embeddings:", model.get_sentence_embedding_dimension())

Dispositivo utilizzato: cuda
GPU: Tesla T4

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Modello caricato correttamente!
Dimensioni degli embeddings: 384

/tmp/ipykernel_749/3006011574.py:19: FutureWarning: The `get_sentence_embedding_dimension` method has been renamed to `get_embedding_dimension`.
  print("Dimensioni degli embeddings:", model.get_sentence_embedding_dimension())

In [5]:
import numpy as np

# Recuperiamo le frasi dal dataset CLiC
sentences = df["sentence"].astype(str).tolist()

print("Numero di frasi:", len(sentences))

# Generazione degli embeddings
embeddings = model.encode(
    sentences,
    batch_size=64,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=True
)

# Controllo del risultato
print("\nEmbeddings generati correttamente!")
print("Dimensioni della matrice:", embeddings.shape)

# Salvataggio della matrice
np.save("jo_march_embeddings.npy", embeddings)

print("File salvato: jo_march_embeddings.npy")

Numero di frasi: 1959

Batches:   0%|          | 0/31 [00:00<?, ?it/s]

Embeddings generati correttamente!
Dimensioni della matrice: (1959, 384)
File salvato: jo_march_embeddings.npy

In [6]:
%pip install -q umap-learn hdbscan

In [7]:
import umap
import numpy as np

# Riduzione dimensionale degli embeddings
reducer = umap.UMAP(
    n_neighbors=15,
    n_components=10,
    min_dist=0.0,
    metric="cosine",
    random_state=42
)

embeddings_umap = reducer.fit_transform(embeddings)

print("Riduzione UMAP completata!")
print("Dimensioni originali:", embeddings.shape)
print("Dimensioni dopo UMAP:", embeddings_umap.shape)

# Salviamo anche la rappresentazione ridotta
np.save("jo_march_embeddings_umap10.npy", embeddings_umap)

print("File salvato: jo_march_embeddings_umap10.npy")

/usr/local/lib/python3.13/dist-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

Riduzione UMAP completata!
Dimensioni originali: (1959, 384)
Dimensioni dopo UMAP: (1959, 10)
File salvato: jo_march_embeddings_umap10.npy

In [8]:
import hdbscan
import numpy as np
import pandas as pd

# Clustering delle frasi su Jo March
clusterer = hdbscan.HDBSCAN(
    min_cluster_size=20,
    min_samples=5,
    metric="euclidean",
    cluster_selection_method="eom"
)

cluster_labels = clusterer.fit_predict(embeddings_umap)

# Aggiungiamo il cluster al dataset originale
df["cluster"] = cluster_labels

# Numero di cluster individuati (escluso il noise)
n_clusters = len(set(cluster_labels) - {-1})

# Frasi non assegnate
n_noise = np.sum(cluster_labels == -1)

print("Clustering HDBSCAN completato!")
print("Numero di cluster individuati:", n_clusters)
print("Frasi non assegnate (noise):", n_noise)
print("Percentuale di noise:", round(n_noise / len(df) * 100, 2), "%")

print("\nDistribuzione delle frasi per cluster:")
print(df["cluster"].value_counts().sort_index())

# Salvataggio dei risultati
df.to_csv("jo_march_clusters.csv", index=False)

print("\nFile salvato: jo_march_clusters.csv")

Clustering HDBSCAN completato!
Numero di cluster individuati: 20
Frasi non assegnate (noise): 663
Percentuale di noise: 33.84 %

Distribuzione delle frasi per cluster:
cluster
-1     663
 0     134
 1      32
 2      33
 3     133
 4      41
 5      69
 6      63
 7      49
 8      38
 9      47
 10    177
 11     68
 12     91
 13     89
 14     35
 15     23
 16     28
 17     97
 18     21
 19     28
Name: count, dtype: int64

File salvato: jo_march_clusters.csv

In [9]:
# Aggiungiamo il grado di appartenenza al cluster
df["cluster_probability"] = clusterer.probabilities_

# Mostriamo le 5 frasi con appartenenza più forte per ogni cluster
for cluster_id in sorted(df["cluster"].unique()):

    if cluster_id == -1:
        continue

    cluster_df = df[df["cluster"] == cluster_id]

    representative = cluster_df.sort_values(
        "cluster_probability",
        ascending=False
    ).head(5)

    print("\n" + "=" * 80)
    print(f"CLUSTER {cluster_id} — {len(cluster_df)} frasi")
    print("=" * 80)

    for _, row in representative.iterrows():
        print(f"\n[{row['novel']}]")
        print(row["sentence"])
        print(f"Probabilità: {row['cluster_probability']:.3f}")

================================================================================
CLUSTER 0 — 134 frasi
================================================================================

[littlewomen]
“I’m the oldest,” began Meg, but Jo cut in with a decided, “I’m the man of the family now Papa is away, and I shall provide the slippers, for he told me to take special care of Mother while he was gone.”
Probabilità: 1.000

[littlewomen]
They all drew to the fire, Mother in the big chair with Beth at her feet, Meg and Amy perched on either arm of the chair, and Jo leaning on the back, where no one would see any sign of emotion if the letter should happen to be touching.
Probabilità: 1.000

[littlewomen]
Jo quite glowed with pleasure at this boyish praise of her sister, and stored it up to repeat to Meg.
Probabilità: 1.000

[littlewomen]
So Meg went away to ‘accept with thanks’, look over her dress, and sing blithely as she did up her one real lace frill, while Jo finished her story, her four apples, and had a game of romps with Scrabble.
Probabilità: 1.000

[littlewomen]
After various lesser mishaps, Meg was finished at last, and by the united exertions of the entire family Jo’s hair was got up and her dress on.
Probabilità: 1.000

================================================================================
CLUSTER 1 — 32 frasi
================================================================================

[littlewomen]
said Jo to herself, when she at length discovered that genuine good will toward one’s fellow men could beautify and dignify even a stout German teacher, who shoveled in his dinner, darned his own socks, and was burdened with the name of Bhaer.
Probabilità: 1.000

[littlewomen]
From her Jo learned it, and liked it all the better because Mr. Bhaer had never told it.
Probabilità: 1.000

[littlewomen]
Poor Jo, how she did glorify that plain man, as she sat knitting away so quietly, yet letting nothing escape her, not even the fact that Mr. Bhaer actually had gold sleeve-buttons in his immaculate wristbands.
Probabilità: 1.000

[littlewomen]
Though a very social man, I think Mr. Bhaer would have gone decorously away, and come again another day, but how could he, when Jo shut the door behind him, and bereft him of his hat?
Probabilità: 1.000

[littlewomen]
“Now, we must finish with Mignon’s song, for Mr. Bhaer sings that,” said Jo, before the pause grew painful.
Probabilità: 1.000

================================================================================
CLUSTER 2 — 33 frasi
================================================================================

[littlewomen]
“I advise you to sail away in one of your ships, and never come home again till you have tried your own way,” said Jo, whose imagination was fired by the thought of such a daring exploit, and whose sympathy was excited by what she called ‘Teddy’s Wrongs’.
Probabilità: 1.000

[littlewomen]
Teddy never seals mine,” said Jo next day, as she distributed the contents of the little post office.
Probabilità: 1.000

[littlewomen]
“Now, Teddy, I want to talk seriously to you about tomorrow,” began Jo, as they strolled away together.
Probabilità: 1.000

[littlewomen]
“And I drink ‘long life to your resolution’, Teddy,” cried Jo, baptizing him with a splash of lemonade, as she waved her glass and beamed approvingly upon him.
Probabilità: 1.000

[littlewomen]
Kiss them, Uncle Teddy,” said wicked Jo.
Probabilità: 1.000

================================================================================
CLUSTER 3 — 133 frasi
================================================================================

[littlewomen]
said Jo, looking disappointed, as Laurie nodded and twinkled with a face full of mysterious intelligence.
Probabilità: 1.000

[littlewomen]
“I don’t tell tales,” replied Laurie, with his ‘high and mighty’ air, as Jo called a certain expression which he occasionally wore.
Probabilità: 1.000

[littlewomen]
You are up to some mischief, Jo,” said Laurie, looking mystified.
Probabilità: 1.000

[littlewomen]
Jo, with perfect faith in her own powers and a friendly desire to make up the quarrel, immediately put a note in the office, inviting Laurie to dinner.
Probabilità: 1.000

[littlewomen]
Don’t say anything till Jo has got good-natured with Laurie, than take a quiet minute and just kiss her, or do some kind thing, and I’m sure she’ll be friends again with all her heart.”
Probabilità: 1.000

================================================================================
CLUSTER 4 — 41 frasi
================================================================================

[littlewomen]
And off went Jo, talking very fast, as she told all about the Hummels, in whom her mother had interested richer friends than they were.
Probabilità: 1.000

[littlewomen]
Jo saw that her mother’s eyes filled and her lips trembled as she spoke, and fearing that she had said too much, she whispered anxiously, “Was it wrong to watch you and to speak of it?
Probabilità: 1.000

[littlewomen]
asked Jo, feeling nearer and dearer to her mother than ever before.
Probabilità: 1.000

[littlewomen]
“I’ve sent for Mother,” said Jo, tugging at her rubber boots with a tragic expression.
Probabilità: 1.000

[littlewomen]
I should have shut the door in his face if he had,” said Jo, settling herself on the floor at her mother’s feet.
Probabilità: 1.000

================================================================================
CLUSTER 5 — 69 frasi
================================================================================

[littlewomen]
Beth had her troubles as well as the others, and not being an angel but a very human little girl, she often ‘wept a little weep’ as Jo said, because she couldn’t take music lessons and have a fine piano.
Probabilità: 1.000

[littlewomen]
While apparently absorbed in her own affairs, Jo watched Beth, and after many conflicting conjectures, finally settled upon one which seemed to explain the change in her.
Probabilità: 1.000

[littlewomen]
She is so funny and dear as she is,” said Beth, who had never betrayed that she was a little hurt at Jo’s having secrets with anyone but her.
Probabilità: 1.000

[littlewomen]
He did like it, so don’t scold, Jo,” said Beth meekly.
Probabilità: 1.000

[littlewomen]
That comes of having big blue eyes and loving music,” said Jo, trying to soothe Beth, who trembled and looked more excited than she had ever been before.
Probabilità: 1.000

================================================================================
CLUSTER 6 — 63 frasi
================================================================================

[littlewomen]
Amy chirped like a cricket, and Jo wandered through the airs at her own sweet will, always coming out at the wrong place with a croak or a quaver that spoiled the most pensive tune.
Probabilità: 1.000

[littlewomen]
Amy teased Jo, and Jo irritated Amy, and semioccasional explosions occurred, of which both were much ashamed afterward.
Probabilità: 1.000

[littlewomen]
Jo heard, but Amy was struggling to her feet and did not catch a word.
Probabilità: 1.000

[littlewomen]
“I never shall forgive you,” was Jo’s stern answer, and from that moment she ignored Amy entirely.
Probabilità: 1.000

[littlewomen]
Jo heard Amy panting after her run, stamping her feet and blowing on her fingers as she tried to put her skates on, but Jo never turned and went slowly zigzagging down the river, taking a bitter, unhappy sort of satisfaction in her sister’s troubles.
Probabilità: 1.000

================================================================================
CLUSTER 7 — 49 frasi
================================================================================

[littlewomen]
Mrs. March broke the silence that followed Jo’s words, by saying in her cheery voice, “Do you remember how you used to play Pilgrims Progress when you were little things?
Probabilità: 1.000

[littlewomen]
“Aunt March had a good fit and sent the supper,” cried Jo, with a sudden inspiration.
Probabilità: 1.000

[littlewomen]
But I am not Miss March, I’m only Jo,” returned the young lady.
Probabilità: 1.000

[littlewomen]
There was an occasional tempest, and once Jo marched home, declaring she couldn’t bear it longer, but Aunt March always cleared up quickly, and sent for her to come back again with such urgency that she could not refuse, for in her heart she rather liked the peppery old lady.
Probabilità: 1.000

[littlewomen]
Jo happened to suit Aunt March, who was lame and needed an active person to wait upon her.
Probabilità: 1.000

================================================================================
CLUSTER 8 — 38 frasi
================================================================================

[littlewomen]
answered Jo.
Probabilità: 1.000

[littlewomen]
asked Jo, who relished the scrape.
Probabilità: 1.000

[littlewomen]
answered Jo, yawning dismally.
Probabilità: 1.000

[littlewomen]
asked Jo, rather hurt.
Probabilità: 1.000

[littlewomen]
asked Jo, who was of an inquiring disposition.
Probabilità: 1.000

================================================================================
CLUSTER 9 — 47 frasi
================================================================================

[littlewomen]
Jo!
Probabilità: 1.000

[littlewomen]
said Jo.
Probabilità: 1.000

[littlewomen]
Jo—Bad.
Probabilità: 1.000

[littlewomen]
demanded Jo.
Probabilità: 1.000

[littlewomen]
said Jo.
Probabilità: 1.000

================================================================================
CLUSTER 10 — 177 frasi
================================================================================

[littlewomen]
“Don’t, Jo.
Probabilità: 1.000

[littlewomen]
“Now don’t forget to keep the bad breadth out of sight, Jo.
Probabilità: 1.000

[littlewomen]
“I don’t see how you can write and act such splendid things, Jo.
Probabilità: 1.000

[littlewomen]
“Don’t you like to dance, Miss Jo?”
Probabilità: 1.000

[littlewomen]
“Right, Jo.
Probabilità: 1.000

================================================================================
CLUSTER 11 — 68 frasi
================================================================================

[littlemen]
So Mrs. Jo soon saw and felt that there was a soft spot in rough Dan, and bided her time to touch and win him.
Probabilità: 1.000

[littlemen]
said Mrs. Jo to herself, as she thought over Dan's late improvement with real satisfaction, yet felt that there was more in the lad than she had at first suspected.
Probabilità: 1.000

[littlemen]
Seeing that they considered it an honor, Mrs. Jo gave it to the one who had earned it, and nobody grumbled when she put her arm on Dan's broad shoulder, saying, with a look that made him color up with pride and pleasure,
Probabilità: 1.000

[littlemen]
“I hope you will,” said Mrs. Jo, for Dan's face had brightened up, and he was so interested in the matter that he forgot his usual taciturnity.
Probabilità: 1.000

[josboys]
Feeling like a thief who has stolen something very precious, Mrs Jo slipped away to her study, and before long Bess followed to report that Dan was fast asleep.
Probabilità: 1.000

================================================================================
CLUSTER 12 — 91 frasi
================================================================================

[littlemen]
“Of course, we do: that's what Aunt Jo has Plumfield for.”
Probabilità: 1.000

[littlemen]
“I'm glad; now come to Aunt Jo.”
Probabilità: 1.000

[littlewomen]
When Aunt spoke to me the other day, she regretted your blunt manners and too independent spirit, and here she writes, as if quoting something you had said—‘I planned at first to ask Jo, but as ‘favors burden her’, and she ‘hates French’, I think I won’t venture to invite her.
Probabilità: 1.000

[littlemen]
“Have you seen Aunt Jo?”
Probabilità: 1.000

[littlemen]
“Aunt Jo, I've done all my lessons, and I can't wait one single minute more!”
Probabilità: 1.000

================================================================================
CLUSTER 13 — 89 frasi
================================================================================

[littlewomen]
cried Jo, taking one up.
Probabilità: 1.000

[littlewomen]
cried Jo.
Probabilità: 1.000

[littlewomen]
cried Jo, as a door slammed and steps sounded in the hall.
Probabilità: 1.000

[littlewomen]
cried Jo, taking up her book.
Probabilità: 1.000

[littlewomen]
cried Jo.
Probabilità: 1.000

================================================================================
CLUSTER 14 — 35 frasi
================================================================================

[littlewomen]
Jo immediately sat up, put her hands in her pockets, and began to whistle.
Probabilità: 1.000

[littlewomen]
And if turning up my hair makes me one, I’ll wear it in two tails till I’m twenty,” cried Jo, pulling off her net, and shaking down a chestnut mane.
Probabilità: 1.000

[littlewomen]
returned Jo, giving her collar a twitch and her head a hasty brush.
Probabilità: 1.000

[littlewomen]
stammered Jo, preparing to back out as speedily as she had bounced in.
Probabilità: 1.000

[littlewomen]
asked Jo, rumpling up her hair, and making herself comfortable.
Probabilità: 1.000

================================================================================
CLUSTER 15 — 23 frasi
================================================================================

[littlewomen]
I wish I hadn’t smashed my coral bracelet, for you might have had it,” said Jo, who loved to give and lend, but whose possessions were usually too dilapidated to be of much use.
Probabilità: 1.000

[littlewomen]
Make the shroud, and lay him in my box, and after the dinner party, we’ll have a nice little funeral,” said Jo, beginning to feel as if she had undertaken a good deal.
Probabilità: 1.000

[littlewomen]
“I haven’t strength of mind enough to clear up now, so we will sober ourselves with a funeral,” said Jo, as they rose, and Miss Crocker made ready to go, being eager to tell the new story at another friend’s dinner table.
Probabilità: 1.000

[littlewomen]
“So am I, but a kind word will govern me when all the king’s horses and all the king’s men couldn’t,” said Jo, trying to say a kind word for her friend, who seemed to get out of one scrape only to fall into another.
Probabilità: 1.000

[littlewomen]
Don’t laugh, Jo, gentlemen really are very necessary aboard ship, to hold on to, or to wait upon one, and as they have nothing to do, it’s a mercy to make them useful, otherwise they would smoke themselves to death, I’m afraid.
Probabilità: 1.000

================================================================================
CLUSTER 16 — 28 frasi
================================================================================

[littlewomen]
Round shoulders had Jo, big hands and feet, a flyaway look to her clothes, and the uncomfortable appearance of a girl who was rapidly shooting up into a woman and didn’t like it.
Probabilità: 1.000

[littlewomen]
He liked Jo, for her odd, blunt ways suited him, and she seemed to understand the boy almost as well as if she had been one herself.
Probabilità: 1.000

[littlewomen]
At any rate, his skill reminds him of the woman he did not like, and so he ‘glowered’ as Jo said.”
Probabilità: 1.000

[littlewomen]
During the bustle Jo had scarcely spoken but flown about, looking pale and wild, with her things half off, her dress torn, and her hands cut and bruised by ice and rails and refractory buckles.
Probabilità: 1.000

[littlewomen]
Jo would turn up her naughty nose at some of the finest, because she has no soul for art, but I have, and I’m cultivating eye and taste as fast as I can.
Probabilità: 1.000

================================================================================
CLUSTER 17 — 97 frasi
================================================================================

[littlewomen]
In spite of her small vanities, Margaret had a sweet and pious nature, which unconsciously influenced her sisters, especially Jo, who loved her very tenderly, and obeyed her because her advice was so gently given.
Probabilità: 1.000

[littlewomen]
Jo had never tried this style before, contenting herself with very mild romances for _The Spread Eagle_.
Probabilità: 1.000

[littlewomen]
Jo’s ambition was to do something very splendid.
Probabilità: 1.000

[littlewomen]
added Jo, who could not, for the life of her, help getting a morsel of fun out of the little sermon, though she took it to heart as much as any of them.
Probabilità: 1.000

[littlewomen]
It isn’t funny, like Jo’s story, but I thought about it a good deal as I came home.
Probabilità: 1.000

================================================================================
CLUSTER 18 — 21 frasi
================================================================================

[littlemen]
said Mrs. Jo, throwing a great chintz curtain down on his head.
Probabilità: 1.000

[littlemen]
Mrs. Jo went on,
Probabilità: 1.000

[littlemen]
added Mrs. Jo.
Probabilità: 1.000

[littlemen]
said Mrs. Jo.
Probabilità: 1.000

[josboys]
said Mrs Jo emphatically.
Probabilità: 1.000

================================================================================
CLUSTER 19 — 28 frasi
================================================================================

[littlewomen]
asked Jo, of a housemaid, who was coming downstairs.
Probabilità: 1.000

[littlewomen]
asked Mrs. Carrol of Jo.
Probabilità: 1.000

[littlewomen]
asked Jo, in a fever of feminine interest and curiosity, for she could not realize it a particle.
Probabilità: 1.000

[littlemen]
asked Mrs. Jo.
Probabilità: 1.000

[littlemen]
asked sly Mrs. Jo, popping the sweeties into her little spool-bag.
Probabilità: 1.000

In [10]:
# Numero di frasi per cluster e per romanzo
cluster_counts = pd.crosstab(
    df["cluster"],
    df["novel"]
)

# Percentuali rispetto al totale delle frasi di ciascun romanzo
cluster_percentages = pd.crosstab(
    df["cluster"],
    df["novel"],
    normalize="columns"
) * 100

print("FREQUENZE ASSOLUTE")
display(cluster_counts)

print("\nPERCENTUALI PER ROMANZO")
display(cluster_percentages.round(2))

FREQUENZE ASSOLUTE

novel    josboys  littlemen  littlewomen
cluster
-1           173        127          363
 0            12          5          117
 1             4         14           14
 2             6         12           15
 3             9          5          119
 4             0          0           41
 5             0          1           68
 6             1          0           62
 7             4          2           43
 8             0          0           38
 9             2          3           42
 10           13          9          155
 11           38         30            0
 12           14         62           15
 13            5          4           80
 14            1          1           33
 15           11          7            5
 16            0          0           28
 17            9          3           85
 18           17          4            0
 19           15         10            3

PERCENTUALI PER ROMANZO

novel    josboys  littlemen  littlewomen
cluster
-1         51.80      42.47        27.38
 0          3.59       1.67         8.82
 1          1.20       4.68         1.06
 2          1.80       4.01         1.13
 3          2.69       1.67         8.97
 4          0.00       0.00         3.09
 5          0.00       0.33         5.13
 6          0.30       0.00         4.68
 7          1.20       0.67         3.24
 8          0.00       0.00         2.87
 9          0.60       1.00         3.17
 10         3.89       3.01        11.69
 11        11.38      10.03         0.00
 12         4.19      20.74         1.13
 13         1.50       1.34         6.03
 14         0.30       0.33         2.49
 15         3.29       2.34         0.38
 16         0.00       0.00         2.11
 17         2.69       1.00         6.41
 18         5.09       1.34         0.00
 19         4.49       3.34         0.23